version: '2.6'

services:
  db:
    #image: mtl-db
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '8000:5432'
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=carrichi@mtl.com
      - PGADMIN_DEFAULT_PASSWORD=carrichi
    ports:
      - '80:80'
    volumes:
      - ./database/servers.json:/pgasmin4/servers.json
      - ./database/pgpass:/pgpass
    depends_on:
      - "db"
  #web:
    #image: nginx:1.23.0-alpine
    #ports:
      #- '8080:80'
    #environment:
      #- NGINX_HOST=meethelight.com
      #- NGINX_PORT=80
